language: node
sudo: false
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - yarn config set registry https://registry.npmjs.org
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
install:
  - yarn install
script:
  - yarn ci
