language: node
sudo: false
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - nvm install 9.2.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
install:
  - $HOME/.yarn/bin/yarn install
script:
  - $HOME/.yarn/bin/yarn ci
